name: Audit

on:
  pull_request:
  push:
    branches: [master]
  schedule:
    - cron: "0 17 * * 5"

jobs:
  scan-packages:
    name: npm audit
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install dependencies
        run: npm ci
      - name: Audit
        uses: oke-py/npm-audit-action@v1.5.0
        with:
          audit_level: moderate
          github_token: ${{ secrets.GITHUB_TOKEN }}
          issue_assignees: oke-py
          issue_labels: vulnerability,test
          dedupe_issues: true
